### ISSUE TITLE
Comment fields

### ISSUE THREAD

**Issue by andreifilep** [boschmotorsport/WinDarab-Documentation#13]
Hello, I was used to use different comment fields as math channels. With 7.07.036 I can not see them in the list any more. I can see them in the Inform window or in the Outing Reports on top of the report, but not able any more to have them available for work.
Is there any workaround for this issue?

Thank you!

**Comment by eohlde** [comment]
Hi Andrei,
Comments are still available in Math Functions, however the channels list does not include them. The Auto-completion still shows them:
![2021-04-05_09h46_59](https://user-images.githubusercontent.com/40407768/113580770-2a598200-95f4-11eb-93ee-c77d87951071.png)

However, I recommend you use [Setupsheets](https://github.com/boschmotorsport/WinDarab/wiki/Setupsheets) instead of Comments. Setupsheets are a newer feature and better suited to this functionality.

**Comment by andreifilep** [comment]
Hello Erich,

that was quick, thank you!

I have tried and I have found following:
(First, I need to re-open formulas to select the channel gain.)
I was using part of comment fields as input for outing report and are not working. This was quite useful for reports as we have had a quick selection of springs / cambers / ARB’s to analyse… Normally, I was using a formula to have the value, like C_SPR_FA is {c_spring_f}
![grafik](https://user-images.githubusercontent.com/45543668/113586020-4594b380-962d-11eb-8d17-3a2817725e7a.png)

I can show the channel, no problem but it does not help…

Can I write the setup data into the setup sheet like in comment fields?
Is it also some sort of text file?

Some other issue I am fighting with is a max value of a math channel.
For example, I am calculating max braking speed and I do not see it correct in the outing report…
Quite strange, as average and min are working fine.
***@***.***D72A38.B527D260]
![grafik](https://user-images.githubusercontent.com/45543668/113586073-58a78380-962d-11eb-9502-8f0e1bd1fb3a.png)


Von: Erich Ohlde ***@***.***>
Gesendet: Montag, 5. April 2021 15:51
An: boschmotorsport/WinDarab ***@***.***>
Cc: AndreiFRE ***@***.***>; Author ***@***.***>
Betreff: Re: [boschmotorsport/WinDarab] Comment fields (#13)


Hi Andrei,
Comments are still available in Math Functions, however the channels list does not include them. The Auto-completion still shows them:
[2021-04-05_09h46_59]<https://user-images.githubusercontent.com/40407768/113580770-2a598200-95f4-11eb-93ee-c77d87951071.png>

However, I recommend you use Setupsheets<https://github.com/boschmotorsport/WinDarab/wiki/Setupsheets> instead of Comments. Setupsheets are a newer feature and better suited to this functionality.

**Comment by eohlde** [comment]
Hi Andrei, 

Did the setupsheets section solve your problem?

**Comment by MartinShort5** [comment]
Hi Erich, Am I able to get version 7.07.026? Thank you
